# Generated by Django 5.2.10 on 2026-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationprofile',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
