# Generated by Django 5.2.10 on 2026-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stationprofile_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
