# Generated by Django 6.0.1 on 2026-02-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stationprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationprofile',
            name='status_online',
            field=models.BooleanField(default=False),
        ),
    ]
