# Generated by Django 6.0.1 on 2026-03-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_stationprofile_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvartalniyDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pogr_this_year', models.IntegerField(default=0)),
                ('pogr_last_year', models.IntegerField(blank=True, null=True)),
                ('vygr_this_year', models.IntegerField(default=0)),
                ('vygr_last_year', models.IntegerField(blank=True, null=True)),
                ('pogr_kont_this_year', models.IntegerField(default=0)),
                ('pogr_kont_last_year', models.IntegerField(blank=True, null=True)),
                ('vygr_kont_this_year', models.IntegerField(default=0)),
                ('vygr_kont_last_year', models.IntegerField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stationprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('station', 'date')},
            },
        ),
        migrations.CreateModel(
            name='KvartalniyMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kunlik_list', models.ManyToManyField(blank=True, to='accounts.kvartalniydaily')),
            ],
        ),
        migrations.CreateModel(
            name='KvartalniyMonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pogr_plan', models.IntegerField(default=0)),
                ('vygr_plan', models.IntegerField(default=0)),
                ('pogr_kont_plan', models.IntegerField(default=0)),
                ('vygr_kont_plan', models.IntegerField(default=0)),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.kvartalniymonthly')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stationprofile')),
            ],
            options={
                'unique_together': {('monthly', 'station')},
            },
        ),
    ]
