# Generated by Django 6.0.1 on 2026-03-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_kvartalniydaily_kvartalniymonthly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvartalniyGroupExtraPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(max_length=50)),
                ('row_name', models.CharField(default='Вес.хоз', max_length=100)),
                ('pogr_plan', models.IntegerField(default=0)),
                ('vygr_plan', models.IntegerField(default=0)),
                ('pogr_kont_plan', models.IntegerField(default=0)),
                ('vygr_kont_plan', models.IntegerField(default=0)),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_extras', to='accounts.kvartalniymonthly')),
            ],
            options={
                'unique_together': {('monthly', 'group_key', 'row_name')},
            },
        ),
    ]
