# Generated by Django 6.0.1 on 2026-03-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_kvartalniygroupextraplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvartalniygroupextraplan',
            name='monthly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_extra_plans', to='accounts.kvartalniymonthly'),
        ),
    ]
