# Generated by Django 6.0.1 on 2026-03-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_kvartalniygroupextraplan_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='pogr_kont_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='pogr_kont_this_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='pogr_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='pogr_this_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='vygr_kont_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='vygr_kont_this_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='vygr_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='vygr_this_year',
            field=models.IntegerField(default=0),
        ),
    ]
