# Generated by Django 6.0.1 on 2026-03-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_kvartalniygroupextraplan_pogr_kont_last_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartalniydaily',
            name='income_last_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='kvartalniydaily',
            name='income_this_year',
            field=models.IntegerField(default=0),
        ),
    ]
