# Generated by Django 6.0.1 on 2026-03-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_kvartalniydaily_income_last_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='income_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='income_plan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='income_this_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniymonthlyplan',
            name='income_plan',
            field=models.IntegerField(default=0),
        ),
    ]
