# Generated by Django 6.0.1 on 2026-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_kvartalniygroupextraplan_income_last_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartalniymonthly',
            name='kunlik_list',
        ),
        migrations.AlterModelOptions(
            name='kvartalniygroupextraplan',
            options={'ordering': ['monthly__date', 'group_key', 'row_name']},
        ),
        migrations.AlterModelOptions(
            name='kvartalniymonthly',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='kvartalniymonthlyplan',
            options={'ordering': ['station__station_name']},
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='income_last_year',
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='income_this_year',
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='pogr_kont_last_year',
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='pogr_kont_this_year',
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='pogr_last_year',
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='pogr_this_year',
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='vygr_kont_last_year',
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='vygr_kont_this_year',
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='vygr_last_year',
        ),
        migrations.RemoveField(
            model_name='kvartalniygroupextraplan',
            name='vygr_this_year',
        ),
        migrations.AlterField(
            model_name='kvartalniygroupextraplan',
            name='row_name',
            field=models.CharField(default='Boshqa Stansiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='kvartalniymonthly',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.DeleteModel(
            name='KvartalniyDaily',
        ),
    ]
