# Generated by Django 6.0.1 on 2026-04-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_kvartalniymonthly_kunlik_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='income_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='income_this_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='pogr_kont_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='pogr_kont_this_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='pogr_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='pogr_this_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='vygr_kont_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='vygr_kont_this_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='vygr_last_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kvartalniygroupextraplan',
            name='vygr_this_year',
            field=models.IntegerField(default=0),
        ),
    ]
