# Generated by Django 5.2.10 on 2026-01-14 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KPIValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value_total', models.IntegerField(default=0)),
                ('value_ktk', models.IntegerField(default=0)),
                ('income', models.BigIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.kpi')),
                ('station_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kpi__order',),
                'unique_together': {('station_user', 'date', 'kpi')},
            },
        ),
        migrations.CreateModel(
            name='StationDailyTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('day', 'день'), ('night', 'ночь'), ('total', 'итог')], max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('station_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_table1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('station_user', 'date', 'shift')},
            },
        ),
    ]
