# Generated by Django 5.2.10 on 2026-01-14 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpivalue',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='kpivalue',
            unique_together={('station_user', 'date')},
        ),
        migrations.AddField(
            model_name='kpivalue',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='kpivalue',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StationDailyTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_table2_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
