# Generated by Django 5.2.10 on 2026-01-14 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_kpivalue_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpivalue',
            options={'ordering': ('kpi__order',)},
        ),
        migrations.AlterModelOptions(
            name='stationdailytable2',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='kpivalue',
            unique_together={('station_user', 'date', 'kpi')},
        ),
        migrations.AddField(
            model_name='stationdailytable2',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stationdailytable2',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationdailytable2',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpivalue',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='stationdailytable2',
            unique_together={('station_user', 'date')},
        ),
        migrations.RemoveField(
            model_name='kpivalue',
            name='data',
        ),
    ]
