# Generated by Django 5.2.10 on 2026-02-13 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_kpivalue_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stationdailytable1',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stationdailytable1',
            name='block',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stationdailytable1',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stationdailytable1',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stationdailytable1',
            unique_together={('station_user', 'date', 'shift', 'block')},
        ),
    ]
